name: Deploy Landing

on:
  push:
    branches: [main]
  workflow_dispatch: # Ручной запуск

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production  # Использует Environment variables из Production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64  # Только для сервера AMD64
          push: true
          build-args: |
            NEXT_PUBLIC_TELEGRAM_CHANNEL_ID=${{ vars.NEXT_PUBLIC_TELEGRAM_CHANNEL_ID }}
            NEXT_PUBLIC_TELEGRAM_BOT_TOKEN=${{ vars.NEXT_PUBLIC_TELEGRAM_BOT_TOKEN }}
            NEXT_PUBLIC_AMPLITUDE_KEY=${{ vars.NEXT_PUBLIC_AMPLITUDE_KEY }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/reflexity-landing:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/reflexity-landing:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/reflexity-landing:latest
          cache-to: type=inline
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🚀 Starting landing deployment..."
            
            # Остановить и удалить старый контейнер
            echo "⏸️  Stopping old container..."
            docker stop reflexity-landing 2>/dev/null || true
            docker rm reflexity-landing 2>/dev/null || true
            
            # Скачать новый образ
            echo "📥 Pulling new image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/reflexity-landing:latest
            
            # Запустить новый контейнер
            echo "▶️  Starting new container..."
            docker run -d \
              --name reflexity-landing \
              --restart unless-stopped \
              -p 3000:3000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/reflexity-landing:latest
            
            # Подождать запуска
            echo "⏳ Waiting for container to start..."
            sleep 5
            
            # Проверить статус
            echo "✅ Checking container status..."
            docker ps | grep reflexity-landing
            
            # Проверить логи
            echo "📋 Recent logs:"
            docker logs --tail=20 reflexity-landing
            
            # Очистить старые образы
            echo "🧹 Cleaning up old images..."
            docker image prune -f
            
            echo "✨ Landing deployment completed!"
      
      - name: Check deployment
        run: |
          echo "🎉 Landing deployed successfully!"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Image: ${{ secrets.DOCKERHUB_USERNAME }}/reflexity-landing:latest"

